### ISSUE TITLE
Annotation to avoid a property being filled in ContentValues

### ISSUE THREAD

**Issue by dianaghele** [gabrielittner/auto-value-cursor#25]
Is there any annotation or something to add to a property in order for it to be left out when building toContentValues?
I would need this for the Ids that are autoincremented primary keys.

Thanks!

**Comment by gabrielittner** [comment]
Currently there isn't a way, but you can add and implement a second `toValues()` method that calls the abstract one and then removes the id or other columns.
```java
@AutoValue public abstract class User {
  abstract String id();
  abstract String name();
  abstract String email();
 
  // you can choose whichever name you want for the method
  abstract ContentValues toCompleteContentValues();

  public ContentValues toContentValues() {
    return toCompleteContentValues().remove("id");
  }
}
```

**Comment by dianaghele** [comment]
Thanks for the info! 

Do you plan to add something to resolve this?

**Comment by gabrielittner** [comment]
You can use the new `@ValuesAdapter` annotation for custom types in `0.4.0-SNAPSHOT` to ignore fields when creating `ContentValues`.

```java
public final class IgnoreFieldAdapter {
  public static ContentValues ignoreField(String s) {
    return null;
  }
}
```

```java
@AutoValue public abstract class User {
  @ValuesAdapter(IgnoreFieldAdapter.class) abstract String id();
  abstract String name();
  abstract String email();

  abstract ContentValues toValues();
}
```

**Comment by DanielHeckrath** [comment]
I'm wondering since ValuesAdapter is no longer a thing, how is this supposed to work with a ColumnTypeAdapter?
