### ISSUE TITLE
Check for null in createFromCursor

### ISSUE THREAD

**Issue by aschober** [gabrielittner/auto-value-cursor#29]
If a non-primitive field has been annotated as nullable, then `createFromCursor(Cursor cursor)` should check `cursor.isNull()`, and if true, return a `null` for that field.

I discovered this issue when inserting `null` for an `Integer` field using `ContentValues.putNull(String key)` while later when retrieving the row, `createFromCursor` returns a `0`.

Related SO questions:
http://stackoverflow.com/questions/8063768
http://stackoverflow.com/questions/18054182/

**Comment by aschober** [comment]
Also on a related note, update `toContentValues` to check fields for nullable annotation and check if field is null and then use `ContentValue.putNull(String key)`.

**Comment by karlicoss** [comment]
+1, just noticed that as well

**Comment by gabrielittner** [comment]
Will be supported in the next release.
