### ISSUE TITLE
Improvement: reusable CursorAdapter class with different column name

### ISSUE THREAD

**Issue by dianaghele** [gabrielittner/auto-value-cursor#33]
For example, I have a couple of objects that contain a Date field and I was wondering if there could be a way to create only one DateCursorAdapter which would use the column name given in the annotation @ColumnName, in order to not create a class for each field that is a Date and has different column name.
This means that I would need to somehow receive the value from @ColumnName in order to use it when processing the cursor.

Would be nice to apply this logic to ValuesAdapter as well.

Thanks!

**Comment by gabrielittner** [comment]
I'll get to it on Sunday. This is also the best solution for #9

**Comment by gabrielittner** [comment]
`0.5.0-SNAPSHOT` has support for it. The readme is already updated to show how adapters work now. It would be great if you could try it out.
