### ISSUE TITLE
Improvement: fillContentValues

### ISSUE THREAD

**Issue by dianaghele** [gabrielittner/auto-value-cursor#34]
I would need, in some cases, to fill in a given ContentValues and return it, instead of creating a new one.
e.g. public abstract ContentValues fillContentValues(ContentValues values);

Could it be possible to add this to the library?

Thanks!

**Comment by NateWickstrom** [comment]
@dianaghele couldn't u just use ContentValues' putAll method for this?  Like:  values.putAll(model.toContentValues())  
...keeping it external, would also give you more control over a conflict resolution strategy

**Comment by gabrielittner** [comment]
I want to keep the number of different entry methods as small as possible, so I'm closing this for now. If you have a good use case for this I may reconsider.
