### ISSUE TITLE
@ColumnAdapter class can't be found at runtime

### ISSUE THREAD

**Issue by mtiidla** [gabrielittner/auto-value-cursor#43]
After upgrading to 0.5.0 I ran into error with Dagger2 as described in #32 and resolved it by upgrading Dagger2 to version 2.4.

Now classes implementing the new ColumnTypeAdapter are valid in generated source code but fail at runtime:

- art - Rejecting re-init on previously-failed class java.lang.Class<.. implements ColumnTypeAdapter>
- dalvik - Link of class '.. implements ColumnTypeAdapter' failed

Any ideas?

**Comment by gabrielittner** [comment]
Do you use `compile` instead of `provided` for the annotations dependency? That changed with 0.5.0.

**Comment by mtiidla** [comment]
Yep, that was missing. with `compile` it works. Thank you!
