### ISSUE TITLE
Default support for Optional without a custom type adapter

### ISSUE THREAD

**Issue by 6bangs** [gabrielittner/auto-value-cursor#47]
To use AutoValue builders with optional properties, you have to use `Optional` (from either Java 8 or Guava); see here: https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#optional

If we try to use `Optional` properties with the auto-value-cursor extension, we get this result:

```
Property "PROPERTY" has type "com.google.common.base.Optional<java.lang.String>" that can't be read from Cursor.
```

It would make sense to coalesce an `Optional` without a value to SQL `NULL` (and vice-versa).

**Comment by 6bangs** [comment]
I've pushed a temporary solution to our fork here: https://github.com/life-beam/auto-value-cursor/commit/48824a10c94214a01cdc52fd18bebdf501a8e76f

It's temporary because I needed to copy [Optionalish](https://github.com/google/auto/blob/1d316fa504f96a9caa5ac93a6074c759cd6140f3/value/src/main/java/com/google/auto/value/processor/Optionalish.java) from AutoValue into auto-value-extension-util. The auto-value-extension-util part of the solution is here: https://github.com/life-beam/auto-value-extension-util/compare/d4b6616264dd4e7a1e728df864c822f05b49f12c...a22b5e8ac33eaa6560a9fef5440156c8a8fd88bc

Finally, I've opened the above referenced issue to see what can be done about making (a version of) `Optionalish` available for use by extensions.

**Comment by gabrielittner** [comment]
While I agree with the feature request, I'd like to avoid copying `Optionalish ` from auto-value. When Google decides on how they'll proceed in the issue you opened I'll happily accept PRs.
