### ISSUE TITLE
Special handling for autogenerated _id columns?

### ISSUE THREAD

**Issue by ened** [gabrielittner/auto-value-cursor#55]
On Android, `_id` columns are usually set as primary keys (`INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL`). 

When I want to read them:
```
@ColumnName("_id") public abstract int getId();
```

Then Auto-Value-Cursor (and auto-value, for that matter) insists on creating a constructor parameter.

As a workaround, I was able to use `@Nullable Integer` and pass `null` to the constructor, but that reads incorrect.

**Comment by gabrielittner** [comment]
What's the behavior you'd expect if we would omit the id field from the constructor? AutoValue would still have a field for id and that field would need a value.

**Comment by rharter** [comment]
The billable approach seems appropriate, since the value is null until
committed to the database. What is your alternate proposal here?

**Comment by ened** [comment]
`@Nullable` approach works, yet semantically it's not correct. `_id` is null *only* for new objects, but *never* for objects actually returned from the database.
Combined with `Builder` classes this is more incorrect, as AutoValue forces me to implement `setId()` there.

`@Generated` ?

**Comment by rharter** [comment]
`@Generated` has no meaning from an AutoValue standpoint. The value has to
either have a value or be nullable. If you create an object without an I'd
via a builder or static factory method, what would that property be set to?
It would have to either return something from `id()`, or return null, in
which case nullable fits.

---------- Forwarded message ---------
