### ISSUE TITLE
@AutoValue dependencies issue?

### ISSUE THREAD

**Issue by adnanali282** [gabrielittner/auto-value-cursor#58]
I have already added gradle dependencies as per your provided instruction, but @AutoValue dependencies not fixed. @ColumnName("name") working properly, but issues with @AutoValue. Please help me. Thanks

Build Environment:
Android studio 2.2.2
distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip

**Comment by gabrielittner** [comment]
Could you post your dependencies block?
