### ISSUE TITLE
Improvement: Register global ColumnAdapters

### ISSUE THREAD

**Issue by danh32** [gabrielittner/auto-value-cursor#59]
Our app makes really heavy use of `BigDecimal` in the models - it would be great if instead of having to copy/paste `@ColumnAdapter(BigDecimalCursorAdapter.class)` on each BigDecimal field that we could just register it once globally, and that ColumnAdapter is invoked for all fields of the specified type.

I'm not super-familiar with the technicals of writing annotation processors, so I'm not 100% sure if this is possible/what it would look like. But it would be great if we could do something similar to Gson's type adapters:

```
AutoValueCursor.registerColumnAdapter(BigDecimal.class, new BigDecimalCursorAdapter());
```

**Comment by JakeWharton** [comment]
It has to be able to be inspected at compile-time so a runtime API won't
work. There could be an annotation processor option that you supply with
the FQCN of the type and the adapter.

**Comment by gabrielittner** [comment]
Is there a way to get processor options that aren't specified in `Processor.getSupportedOptions()`? Otherwise we'd need a change to the extension API to request options.

**Comment by JakeWharton** [comment]
Nope. I guess it'll have to come with an extension API change.
