### ISSUE TITLE
Improvement: support ColumnTypeAdapters with identical names

### ISSUE THREAD

**Issue by dianaghele** [gabrielittner/auto-value-cursor#60]
For example, I have an object Vehicle which contains a field of type Price with its ColumnTypeAdapter and another field of type Owner with its ColumnTypeAdapter. I want to declare these adapters in the corresponding classes and use them both in the Vehicle class. 

The problem is that when this extension generates the method createFromCursor(Cursor) it declares the columnAdapter variables with the same name and I receive the error:

Error:(26, 33) error: variable columnAdapter is already defined in method createFromCursor(Cursor)

and the generated code:

...
Price.ColumnAdapter columnAdapter = new Price.ColumnAdapter();
Owner.ColumnAdapter columnAdapter = new Owner.ColumnAdapter();
...

e.g.

@AutoValue
public class Vehicle {
	@ColumnAdapter(Price.ColumnAdapter.class)
	Price price();
       @ColumnAdapter(Owner.ColumnAdapter.class)
	Owner owner();
}

@AutoValue
public class Price {
   ....
	public static class ColumnAdapter implements ColumnTypeAdapter<Price> {
              ....
	}
}
@AutoValue
public class Owner {
   ....
	public static class ColumnAdapter implements ColumnTypeAdapter<Owner> {
              ....
	}
}

From my testing, auto-value-parcel already handles this case.

Can you make the extension support identical names? 

Thanks!
Diana

**Comment by gabrielittner** [comment]
It should be fairly easy to fix using javapoet's `NameAllocator`. I'll try to find some time this weekend or next week. Also happy about a pull request if you want to give it a go.

**Comment by dianaghele** [comment]
Awesome ^_^

Going to Droidcon Italy so I don't think I'll have the time this week. Maybe next week, if you'll not make a release until then :)

**Comment by dianaghele** [comment]
Hello :) 

I saw that you made some changes to the library to support identical names...Do you want to fix or change anything else before publishing a release? Or when will these changes be available?

Thanks!
DG

**Comment by gabrielittner** [comment]
It's on my todo list for today :)

**Comment by dianaghele** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/7548831-205502762_1-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by dianaghele** [comment]
Awesome! Thanks a lot ^_^

**Comment by gabrielittner** [comment]
1.1.0 is out

**Comment by dianaghele** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/7834193-205502762_1-s4-v1.png?transparent=1&palette=1&width=246)
