### ISSUE TITLE
Improvement: Support to ignore fields

### ISSUE THREAD

**Issue by nevess** [gabrielittner/auto-value-cursor#61]
Add support to ignore fields in the fromCursor and toContentValues implementation.

**Comment by gabrielittner** [comment]
You can use ColumnTypeAdapters that don't read or write anything to achieve this. Beyond that I have no plans to support ignoring fields.

**Comment by luisyng** [comment]
Hi @gabrielittner,

I am trying to to follow the approach you suggested, but I am having issues with the types.

I have implemented a generic `ColumnTypeAdapter`: 

```
public abstract class IgnoreColumnAdapter<T> implements ColumnTypeAdapter<T> {

    public final T fromCursor(Cursor cursor, String columnName) {
        return null;
    }
    public final void toContentValues(ContentValues values, String columnName, T value) {
    }
}
```

Having this class: 
```
public class User {
    // Column needs to be ignored
    public abstract UserCredentials userCredentials();
}
```
I have to create an specific `class IgnoreUserCredentialsAdapter extends IgnoreColumnAdapter<UserCredentials>` to ensure the generated code in `fromCursor()` has the expected type. 

We have many types we would like to ignore. Is there a way to achieve this without creating an specific type for each of them?

Thanks a lot!
